game:
  title: "Turn-Based Strategy Game"
  window:
    width: 800
    height: 600
  grid:
    cell_size: 64
    width: 10  # Should match the level width
    height: 8  # Should match the level height

controls:
  cursor_up: "UP"
  cursor_down: "DOWN"
  cursor_left: "LEFT"
  cursor_right: "RIGHT"
  select_action: "SPACE"
  move_action: "m"
  attack_action: "a"
  pass_turn: "p"
  quit_game: "ESCAPE"  # New control for quitting the game

highlights:
  move_range: [0, 0, 200, 100]  # Blue with transparency
  attack_range: [255, 100, 100, 100]  # Light red with transparency

# Define terrain mappings (character to terrain type)
terrain_mapping:
  "H": "hill"
  "M": "mountain"
  "F": "forest"
  ".": "plains"  # Added a plains terrain type

# Define the levels
levels:
  - name: "Level 1"
    description: "A simple starting level"
    # Each string represents a row, each character represents a terrain
    layout:
      - ".........."
      - ".........."
      - ".........."
      - "..FMMM...."
      - "...FF....."
      - ".....FFFFF."
      - "H.....FFFF."
      - "HH........."
    # Player starting positions (list of [x, y] coordinates)
    player_units:
      - [0, 0, "melee"]
      - [1, 0, "ranged"]
      - [2, 0, "melee"]
    # Enemy starting positions (list of [x, y] coordinates)
    enemy_units:
      - [5, 5, "melee"]
      - [5, 6, "melee"]
  
  - name: "Level 2"
    description: "A more challenging level"
    layout:
      - "MMMM......"
      - "MMMM......"
      - "..FF......"
      - "..FFF....."
      - ".....FFFFF."
      - ".....FFFFF."
      - "HH.....FFF."
      - "HHH......."
    player_units:
      - [0, 0, "melee"]
      - [1, 0, "ranged"]
      - [0, 1, "melee"]
    enemy_units:
      - [8, 6, "ranged"]
      - [9, 6, "melee"]
      - [9, 7, "ranged"]
      - [8, 7, "melee"]

terrain_types:
  hill:
    color: [100, 200, 100]
    movement_cost: 1
    description: "Rolling hills with short grass"
  mountain:
    color: [150, 150, 150]
    movement_cost: 2
    description: "Rocky mountain terrain, difficult to traverse"
  forest:
    color: [0, 100, 0]
    movement_cost: 1
    description: "Dense forest with tall trees"
  plains:
    color: [180, 230, 180]
    movement_cost: 1
    description: "Flat open terrain, easy to traverse"

unit_types:
  melee:
    strength: 2
    range: 1
    hp: 3
    move: 3
    color: [255, 0, 0]
    description: "Close combat warrior"
  ranged:
    strength: 1
    range: 2
    hp: 1
    move: 2
    color: [0, 0, 255]
    description: "Attacks from distance"
